[workspace]
resolver = "3"
members = ["crates/*"]
default-members = ["crates/in-typ-bot"]

[workspace.package]
version = "0.0.0"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
nursery = "warn"
