[package]
name = "in-typ-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.7"
dotenvy_macro = "0.15.7"
indoc = "2.0.5"
itertools = "0.13.0"
svg = "0.18.0"
teloxide = { version = "0.13.0", features = ["macros"] }
thiserror = "2.0.3"
tokio = { version = "1.41.1", features = [
  "macros",
  "process",
  "rt-multi-thread",
] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
uuid = { version = "1.11.0", features = ["fast-rng"] }

[lints.clippy]
all = "warn"
pedantic = "warn"
nursery = "warn"
